services:
  jenkins:
    build: .
    container_name: jenkins
    privileged: true
    ports:
      - "8190:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - JENKINS_ADMIN_USER=${JENKINS_ADMIN_USER}
      - JENKINS_ADMIN_NAME=${JENKINS_ADMIN_NAME}
      - JENKINS_ADMIN_EMAIL=${JENKINS_ADMIN_EMAIL}
      - JENKINS_URL=${JENKINS_URL}
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      - DSL_JOB_ID=${DSL_JOB_ID}
      - DSL_JOB_URL=${DSL_JOB_URL}
